CREATE TABLE IF NOT EXISTS swap_history (
    id SERIAL PRIMARY KEY,
    "startTime" BIGINT NOT NULL,
    "endTime" BIGINT NOT NULL,
    "toAssetCount" BIGINT NOT NULL,
    "toRuneCount" BIGINT NOT NULL,
    "toTradeCount" BIGINT NOT NULL,
    "fromTradeCount" BIGINT NOT NULL,
    "synthMintCount" BIGINT NOT NULL,
    "synthRedeemCount" BIGINT NOT NULL,
    "totalCount" BIGINT NOT NULL,
    "toAssetVolume" BIGINT NOT NULL,
    "toRuneVolume" BIGINT NOT NULL,
    "toTradeVolume" BIGINT NOT NULL,
    "fromTradeVolume" BIGINT NOT NULL,
    "synthMintVolume" BIGINT NOT NULL,
    "synthRedeemVolume" BIGINT NOT NULL,
    "totalVolume" BIGINT NOT NULL,
    "toAssetVolumeUsd" DECIMAL(18, 8) NOT NULL,
    "toRuneVolumeUsd" DECIMAL(18, 8) NOT NULL,
    "toTradeVolumeUsd" DECIMAL(18, 8) NOT NULL,
    "fromTradeVolumeUsd" DECIMAL(18, 8) NOT NULL, 
    "synthMintVolumeUsd" DECIMAL(18, 8) NOT NULL,
    "synthRedeemVolumeUsd" DECIMAL(18, 8) NOT NULL,
    "totalVolumeUsd" DECIMAL(18, 8) NOT NULL,
    "toAssetFees" BIGINT NOT NULL,
    "toRuneFees" BIGINT NOT NULL,
    "toTradeFees" BIGINT NOT NULL,
    "fromTradeFees" BIGINT NOT NULL,
    "synthMintFees" BIGINT NOT NULL,
    "synthRedeemFees" BIGINT NOT NULL,
    "totalFees" BIGINT NOT NULL,
    "toAssetAverageSlip" DECIMAL(18, 8) NOT NULL,
    "toRuneAverageSlip" DECIMAL(18, 8) NOT NULL,
    "toTradeAverageSlip" DECIMAL(18, 8) NOT NULL, 
    "fromTradeAverageSlip" DECIMAL(18, 8) NOT NULL,
    "synthMintAverageSlip" DECIMAL(18, 8) NOT NULL,
    "synthRedeemAverageSlip" DECIMAL(18, 8) NOT NULL,
    "averageSlip" DECIMAL(18, 8) NOT NULL,
    "runePriceUsd" DECIMAL(18, 8) NOT NULL,
    UNIQUE ("startTime", "endTime")
);