#![allow(non_snake_case)]
use serde::{Deserialize, Serialize};
use sqlx::FromRow;

#[derive(Debug, Serialize, Deserialize, FromRow)]
pub struct SwapInterval {
    pub averageSlip: String,
    pub endTime: String,
    pub fromSecuredAverageSlip: String,
    pub fromSecuredCount: String,
    pub fromSecuredFees: String,
    pub fromSecuredVolume: String,
    pub fromSecuredVolumeUSD: String,
    pub fromTradeAverageSlip: String,
    pub fromTradeCount: String,
    pub fromTradeFees: String,
    pub fromTradeVolume: String,
    pub fromTradeVolumeUSD: String,
    pub runePriceUSD: String,
    pub startTime: String,
    pub synthMintAverageSlip: String,
    pub synthMintCount: String,
    pub synthMintFees: String,
    pub synthMintVolume: String,
    pub synthMintVolumeUSD: String,
    pub synthRedeemAverageSlip: String,
    pub synthRedeemCount: String,
    pub synthRedeemFees: String,
    pub synthRedeemVolume: String,
    pub synthRedeemVolumeUSD: String,
    pub toAssetAverageSlip: String,
    pub toAssetCount: String,
    pub toAssetFees: String,
    pub toAssetVolume: String,
    pub toAssetVolumeUSD: String,
    pub toRuneAverageSlip: String,
    pub toRuneCount: String,
    pub toRuneFees: String,
    pub toRuneVolume: String,
    pub toRuneVolumeUSD: String,
    pub toSecuredAverageSlip: String,
    pub toSecuredCount: String,
    pub toSecuredFees: String,
    pub toSecuredVolume: String,
    pub toSecuredVolumeUSD: String,
    pub toTradeAverageSlip: String,
    pub toTradeCount: String,
    pub toTradeFees: String,
    pub toTradeVolume: String,
    pub toTradeVolumeUSD: String,
    pub totalCount: String,
    pub totalFees: String,
    pub totalVolume: String,
    pub totalVolumeUSD: String,
}
